//--------------------------------------------------
// Enumerations of User Timer Events
//--------------------------------------------------
    _USER_TIMER_EVENT_KEY_REPEAT_ENABLE,
    _USER_TIMER_EVENT_KEY_SCAN_READY,
#if (_PRODUCT_ID_SEL == RTD2556_CANON_1201_RL6432_156PIN_A_G101ICE_L01_LVDS_PWM)    
    _USER_TIMER_EVENT_SCALER_MCU_CHECK,
    //_USER_TIMER_EVENT_SCALER_MCU_RX,    
    //_USER_TIMER_EVENT_SCALER_MCU,
    _USER_TIMER_EVENT_SCALER_MCU_WRITE, 
#endif    
    _USER_TIMER_EVENT_OSD_DISABLE_OSD_LOGO,
    _USER_TIMER_EVENT_OSD_SHOW_NO_CABLE,
    _USER_TIMER_EVENT_OSD_SHOW_NO_SIGNAL,
    _USER_TIMER_EVENT_OSD_SHOW_POWER_SAVING,
    _USER_TIMER_EVENT_GO_TO_POWER_SAVING,
    _USER_TIMER_EVENT_OSD_DISABLE,
    _USER_TIMER_EVENT_PANEL_BACKLIGHT_ON,
    _USER_TIMER_EVENT_PANEL_POWER_OFF,
    _USER_TIMER_EVENT_DO_AUTO_COLOR,
    _USER_TIMER_EVENT_PANEL_USED_TIMER,
    _USER_TIMER_EVENT_SYSTEM_RUN_USED_TIMER,

#if(_HIGHLIGHT_WINDOW_SUPPORT == _ON)
    _USER_TIMER_EVENT_HLWIN_TYPE5_MOVE,
#endif

    _USER_TIMER_EVENT_OSD_KEYINFO_UNHIGHLIGHT,
    _USER_TIMER_EVENT_OSD_SHOW_DP_VERSION_SELECT,

#if(_HDMI_CEC_SUPPORT == _ON)
    _USER_TIMER_EVENT_CEC_LA_POLLING,
#endif

#if(_FREESYNC_SUPPORT == _ON)
    _USER_TIMER_EVENT_OSD_SHOW_FREESYNC_VFREQ,
#endif

#if(_FREEZE_SUPPORT == _ON)
    _USER_TIMER_EVENT_OSD_DISABLE_FREEZE_MSG,
#endif

#if(_LD_HDR10_BOOST_SUPPORT == _ON)
     _USER_TIMER_EVENT_HDR_BOOST,
     _USER_TIMER_EVENT_HDR_COOL,
#endif

    _USER_TIMER_EVENT_BURN_IN,
    _USER_TIMER_EVENT_OSD_SAVE_USER2_DATA,
    _USER_TIMER_EVENT_BACKLIGHT_SENSOR_HANDLER,
    _USER_TIMER_EVENT_BACKLIGHT_SENSOR_SPEEDY_TIMER,
    _USER_TIMER_EVENT_BACKLIGHT_SENSOR_VALUE_UPDATE,

    _USER_TIMER_EVENT_COLOR_SENSOR_CALIBRATION_MODE,
    _USER_TIMER_EVENT_FSENSOR_MTCSCDCAF_MEASUREMENT_END,
    _USER_TIMER_EVENT_AMBI_SENSOR_ADC_START,
    _USER_TIMER_EVENT_AMBI_SENSOR_HANDLER,
    _USER_TIMER_EVENT_DISTANCESENSOR_HANDLER,
    _USER_TIMER_EVENT_GRAVITYSENSOR_HANDLER,    
    //_USER_TIMER_EVENT_LIGHTBOXMODE_LONG_PRESS,
    _USER_TIMER_EVENT_DO_LOCAL_ENHANCEMENT,
    _USER_TIMER_EVENT_SYSTEM_POWER_ONOFF,
    _USER_TIMER_EVENT_KEY_BEEP_READY,
    _USER_TIMER_EVENT_KEY_LOCK_COUNT,
    _USER_TIMER_EVENT_KEY_LOCK_OSD_MSG,
    _USER_TIMER_EVENT_KEY_PLUS_LUMINANCE_DISPLAY_MODE,
    _USER_TIMER_EVENT_KEY_PLUS_LUMINANCE_DISPLAY_MODE_END,
    _USER_TIMER_EVENT_AC_ON_TEST_IMAGE_DISPLAY,
    _USER_TIMER_EVENT_AC_ON_TEST_IMAGE_DISPLAY_TIME,
    _USER_TIMER_EVENT_TEST_IMAGE_DISPLAY_PATCH,
    _USER_TIMER_EVENT_COLOR_ADAPTIVE_IMAGE_HANDLER,
    _USER_TIMER_EVENT_SET_LUT_DATA,    
    _USER_TIMER_EVENT_QA_EVENT,
    _USER_TIMER_EVENT_CALIBRATION_LUX_COMPLETE, 
    _USER_TIMER_EVENT_NOTIFY_MCU_UPDATE_FPGA,    
    _USER_TIMER_EVENT_LIGHTBOX_OSD_DISABLE,
    _USER_TIMER_EVENT_COLORMONO_LONG_PRESS,
    _USER_TIMER_EVENT_SET_KVM_DISPLAY_MODE,

